# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
