# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20160215_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comments_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rateset',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Item', unique=True),
        ),
    ]
