# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20160218_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='catalogue.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
