# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20160215_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateset',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Item'),
        ),
    ]
