# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20160215_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateset',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
