# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20160225_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.ImageField(default=b'', upload_to=b''),
        ),
    ]
