# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20160225_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.ImageField(default=b'/static/images.jpg', upload_to=b''),
        ),
    ]
