# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20160215_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='average_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=6),
        ),
    ]
