# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20160216_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateset',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Item'),
        ),
        migrations.AlterField(
            model_name='rateset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
