# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20160216_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rates_total',
            field=models.IntegerField(default=0),
        ),
    ]
