# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('activity_status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
                'db_table': 'stores',
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
    ]
