# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['title'], 'verbose_name': 'store', 'verbose_name_plural': 'stores'},
        ),
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
    ]
