# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='start',
            field=models.DateField(default=datetime.datetime(2016, 3, 1, 8, 21, 5, 554663, tzinfo=utc)),
        ),
    ]
